#!/bin/python
# -*- coding: utf-8 -*-
import delijnosmlib
import unittest
from tkinter import Tk

class KnownValues(unittest.TestCase):                          
    knownValues = (
        ("Aaigem RVT St-Vincentius", "Aaigem RVT Sint-Vincentius","01"),
        ("Aalst Kon. Tech. Atheneum 1", "Aalst Koninklijk Technisch Atheneum 1","01"),
        ("Aalst Lion D'Or", "Aalst Lion d'Or","01"),
        ("Aalst O. Dendermondsestwg", "Aalst Ouden Dendermondsesteenweg","01"),
        ("Aarschot Haterbeek kerk", "Aarschot Haterbeek Kerk","01"),
        ("Aarschot Nieuwrodesestwg", "Aarschot Nieuwrodesesteenweg","01"),
        ("Aarsele 'T Hoge", "Aarsele 't Hoge","01"),
        ("Aartrijke 'T Veld", "Aartrijke 't Veld","01"),
        ("Aartselaar G. Gezellestraat", "Aartselaar Guido Gezellestraat","01"),
        ("Aartselaar J. Davidlaan", "Aartselaar Jan Davidlaan","01"),
        ("Aartselaar J. Stobbaertslaan", "Aartselaar Jan Stobbaertslaan","01"),
        ("Aartselaar P. Benoitlaan", "Aartselaar Peter Benoitlaan","01"),
        ("Achterbroek K. Van Thillostraat", "Achterbroek Karel Van Thillostraat", "52"), 
        ("Adegem Dr. Herreboutlaan", "Adegem Dokter Herreboutlaan","01"),
        ("Anderlecht De Linde Plein", "De Lindeplein", "20"),
        ("Anderlecht Hospitaal J.Bracops", "Hospitaal Joseph Bracops", "20"),
        ("Anderlecht Kol.Veteranensquare", "Koloniale Veteranen - Vétérans Coloniaux","20"),
        ("Anderlecht R. Henry", "René Henry", "20"),
        ("Anderlecht Sint-Niklaas", "Saint-Nicolas - Sint-Niklaas", "20"),
        ("Antwerpen F. Rooseveltplaats", "Franklin Rooseveltplaats","01"),
        ("Antwerpen G. Le Grellelaan", "Gerard Le Grellelaan","01"),
        ("Antwerpen J. Van Rijswijcklaan", "Jan Van Rijswijcklaan","01"),
        ("Antwerpen Premetrostation Astrid", "Astrid","01"),
        ("Antwerpen Premetrostation Elisabeth", "Elisabeth","01"),
        ("Antwerpen Premetrostation Groenplaats", "Groenplaats","01"),
        ("Antwerpen Premetrostation Handel", "Handel","01"),
        ("Antwerpen Premetrostation Meir", "Meir","01"),
        ("Antwerpen Premetrostation Opera", "Opera","01"),
        ("Antwerpen Premetrostation Schijnpoort", "Schijnpoort","01"),
        ("Antwerpen Premetrostation Sport", "Sport","01"),
        ("Antwerpen Premetrostation Van Eeden", "Van Eeden","01"),
        ("Antwerpen R. Veremanstraat", "Renaat Veremansstraat","01"),
        ("Antwerpen Station Zuid", "Antwerpen Station Zuid","01"),
        ("Antwerpen Stwg. op Stabroek", "Steenweg op Stabroek","01"),
        ("Appels T Zand", "Appels 't Zand","01"),
        ("As Onze Lieve Vrouwstraat", "As Onze-Lieve-Vrouwstraat","01"),
        ("Asse Terheiden,Lindestr.", "Asse Terheiden, Lindestraat","01"),
        ("Assebroek Az Sint-Lucas (Op Terrein)", "Assebroek AZ Sint-Lucas (Op Terrein)","01"),
        ("Assebroek C.V.D. Bussche", "Assebroek Camiel Van den Bussche","01"),
        ("Assebroek O.L.V. College", "Assebroek Onze-Lieve-Vrouwcollege","01"),
        ("Baal S.J. Ceulemansstraat", "Baal S. Jos Ceulemansstraat","01"),
        ("Baarle-Hertog Zondereigen kerk", "Baarle-Hertog Zondereigen Kerk","01"),
        ("Baarle-Nassau Sint-Janstraat", "Baarle-Nassau Sint-Janstraat","01"),
        ("Baarle-Nassau W. Alexanderstraat", "Baarle-Nassau Willem Alexanderstraat","01"),
        ("Balen B. Leysenlaan", "Balen Bert Leysenlaan","01"),
        ("Bazel Rupelmondestr./Nieuwe Baan", "Bazel Rupelmondestraat/Nieuwe Baan","01"),
        ("Bassenge Reu Neuve Chapelle", "Bassenge Rue Neuve Chapelle","01"),
        ("Beernem 'T Hof", "Beernem 't Hof","01"),
        ("Beernem Knesselarestwg", "Beernem Knesselaresteenweg","01"),
        ("Beernem M.Sabbestraat", "Beernem Maurits Sabbestraat","01"),
        ("Beerse Den Hout kerk", "Beerse Den Hout Kerk","01"),
        ("Beerzel  Augustijnenlei", "Beerzel Augustijnenlei","01"),
        ("Begijnendijk O.L.V.-straat", "Begijnendijk Onze-Lieve-Vrouwstraat","01"),
        ("Berendrecht Stwg. Zandvliet", "Berendrecht Steenweg Zandvliet","01"),
        ("Berlaar Melkouwen  Station", "Berlaar Melkouwen Station","01"),
        ("Berlare CC Stroming", "Berlare Cultureel Centrum Stroming","01"),
        ("Betekom C. Vissenaekenplein", "Betekom Cornelius Vissenaekensplein","01"),
        ("Betekom kerk", "Betekom Kerk","01"),
        ("Beveren 'T Meersenhof", "Beveren 't Meersenhof","01"),
        ("Beveren A.Z. Nikolaas", "Beveren AZ Nikolaas","01"),
        ("Beveren J. Van Hoofstraat", "Beveren Jef Van Hoofstraat","01"),
        ("Beveren L. Mortelmansstraat", "Beveren Lodewijk Mortelmansstraat","01"),
        ("Beveren O-L-Vrouwkerk", "Beveren Onze-Lieve-Vrouwkerk","01"),
        ("Bierges Chem. d Angoussart", "Bierges Chemin d'Angoussart","01"),
        ("Bierges Rue Th.Piat", "Bierges Rue Théophile Piat","01"),
        ("Binkom Stwg naar Attenrode", "Binkom Steenweg naar Attenrode","01"),
        ("Blankenberge Serg. De Bruynestr.", "Blankenberge Sergeant De Bruynestraat","01"),
        ("Boechout Dr. T. Tutsstraat", "Boechout Dokter Theo Tutsstraat","66"),
        ("Boechout J.F. Willemsstraat", "Boechout Jan Frans Willemsstraat","66"),
        ("Boechout Sint-Gabrielstraat", "Boechout Sint-Gabriëlstraat", "66"), 
        ("Bonheiden  Gestellei", "Bonheiden Gestellei","01"),
        ("Bonheiden  IJzerenveld", "Bonheiden IJzerenveld","01"),
        ("Bonheiden P. Benoitlaan", "Bonheiden Peter Benoitlaan","01"),
        ("Bonheiden Waversestwg.", "Bonheiden Waversesteenweg","01"),
        ("Boom 's-Herenbaan", "Boom 's Herenbaan","01"),
        ("Boom E. Vanderveldestraat", "Boom Emile Vanderveldestraat","01"),
        ("Borgerhout J. Posenaerstraat", "Jozef Posenaerstraat","01"),
        ("Borgerhout K. Van De Woestijnelei", "Karel Van de Woestijnelei","01"),
        ("Borgerhout L. Van Berckenlaan", "Lodewijk Van Berckenlaan","01"),
        ("Borgerhout W. Woodstraat", "William Woodstraat","01"),
        ("Bornem P. Colomalaan", "Bornem Pedro Colomalaan", "45"),
        ("Borsbeek J. Reusenslei", "Jozef Reusenslei","01"),
        ("Borsbeke Ijzerenwegstraat", "Borsbeke IJzerenwegstraat","01"),
        ("Bottelare Kon. Astridlaan", "Bottelare Koningin Astridlaan","01"),
        ("Brasschaat Berrelei", "Brasschaat Berrélei", "42"), 
        ("Brasschaat Donk kerk", "Brasschaat Donk Kerk","42"),
        ("Brecht H. Schoofsstraat", "Brecht Hendrik Schoofsstraat","01"),
        ("Bredene Aug.Plovieplein", "Bredene August Plovieplein","01"),
        ("Broechem Van Den Nestlaan", "Broechem Van den Nestlaan","01"),
        ("Brugge  Jh Herdersbrug", "Brugge Jeugdherberg Herdersbrug","01"),
        ("Brugge 'T Boompje", "Brugge 't Boompje","01"),
        ("Brugge C.Everaartstraat", "Brugge Cornelis Everaartstraat","01"),
        ("Brugge Industriezone Bl Toren", "Brugge Industriezone Blauwe Toren","01"),
        ("Haasrode Industr. Interleuvenlaan", "Haasrode Industriezone Interleuvenlaan","01"),
        ("Brugge J.&M. Sabbestraat", "Brugge Julius en Maurits Sabbestraat","01"),
        ("Brugge Karel De Stoute", "Brugge Karel de Stoute","01"),
        ("Brugge N. Gombertstraat", "Brugge Nikolaas Gombertstraat","01"),
        ("Brugge N.Gombertstraat", "Brugge Nikolaas Gombertstraat","01"),
        ("Brugge O.L.V. Kerk", "Brugge Onze-Lieve-Vrouwekerk","01"),
        ("Brugge Ocmw-Molenerf", "Brugge OCMW Molenerf","01"),
        ("Brugge P. De Halleux", "Brugge Paul De Halleux","01"),
        ("Brugge Sint-Pieters Station", "Brugge Sint-Pietersstation","01"),
        ("Brussel Albert-II-laan", "Albert II-laan", "20"),
        ("Brussel Magnolia", "Magnolia - Magnolias", "20"), 
        ("Brussel Modelwijk 4", "Modelwijk 4 - Cité Modèle 4","20"),
        ("Brussel Noord perron 6", "Brussel Noordstation Perron 6","20"),
        ("Brussel Zuid perron 6", "Brussel Zuidstation Perron 6","20"),
        ("Cdt.", "Commandant","01"),
        ("Dadizele 'T Hoge", "Dadizele 't Hoge","01"),
        ("Dentergem Rvt Mariaburcht", "Dentergem RVT Mariaburcht","01"),
        ("Dessel Perestraat", "Dessel Peresstraat","01"),
        ("Deurne Langestraat II", "Langestraat II","01"),
        ("Deurne Molenberg", "Molenberg","01"),
        ("Deurne Stationstraat", "Stationstraat","01"),
        ("Deurne Steenweg op Engsbergen", "Steenweg op Engsbergen","01"),
        ("Diksmuide Ijzerbrug", "Diksmuide IJzerbrug","01"),
        ("Dilbeek H.Moeremanslaan", "Dilbeek Henri Moeremanslaan","01"),
        ("Drieslinter Stwg op Melkwezer", "Drieslinter Steenweg op Melkwezer","01"),
        ("Dudzele 'T Apertje", "Dudzele 't Apertje","01"),
        ("Duffel Mijlstraat kerk", "Duffel Mijlstraat Kerk","01"),
        ("Edegem W. Herreynsstraat", "Edegem Willem Herreynsstraat","01"),
        ("Eernegem 'S Gravendriesschelaan", "Eernegem 's Gravendriesschelaan","01"),
        ("Eernegem Lp Boon", "Eernegem Louis Paul Boon","01"),
        ("Eke 'S Gravendreef", "Eke 's Gravendreef","01"),
        ("Ekeren Donk kerk", "Ekeren Donk Kerk","01"),
        ("Ekeren F. Verbieststraat", "Ferdinand Verbieststraat","01"),
        ("Ekeren G. Stijnenlaan", "Gerardus Stijnenlaan","01"),
        ("Ekeren K. De Wintstraat", "Karel De Wintstraat","01"),
        ("Elsene VUB Gebouw M inrit 11", "VUB Gebouw M Inrit 11","01"),
        ("Emael Ecole de l' Etat", "Emael École de l'État","01"),
        ("Erembodegem D'Uitseweg", "Erembodegem d'Uitseweg","01"),
        ("Erembodegem Ijzerenwegstraat", "Erembodegem IJzerenwegstraat","01"),
        ("Erps-Kwerps D'Ieteren", "Erps-Kwerps D'Ieteren","07"),
        ("Erps-Kwerps Huis nr. 53", "Erps-Kwerps Huis nummer 53","01"),
        ("Ganshoren H.Hart College", "Heilig Hart College - Collège Sacré Coeur","01"),
        ("Geel AZ Sint-Dimpna", "Geel AZ Sint-Dimpna","01"),
        ("Geel Dr. Sanodreef", "Geel Dokter Sanodreef","01"),
        ("Geel Larum kerk", "Geel Larum Kerk","01"),
        ("Geel P. Van Neylenstraat", "Geel Pastoor Van Neylenstraat","01"),
        ("Geel Punt kerk", "Geel Punt Kerk","01"),
        ("Genk d' Ierd", "Genk d'Ierd","01"),
        ("Gent M. Middelares - Maalte", "Maria Middelares - Maalte","01"),
        ("Gent Opgeeistenlaan", "Opgeëistenlaan","01"),
        ("Grobbendonk  Hildering", "Grobbendonk Hildering","01"),
        ("Haacht kerk", "Haacht Kerk","01"),
        ("Haaltert Burg. De Saedeleerstraat", "Haaltert Burgemeester De Saedeleerstraat","01"),
        ("Halle AZ.Sint-Maria", "Halle AZ Sint-Maria","01"),
        ("Halluin Hotel De Ville", "Halluin Hôtel De Ville","01"),
        ("Halluin Monument Aux Morts", "Halluin Monument aux Morts","01"),
        ("Hasselt De Geloesplein", "Hasselt de Geloesplein","01"),
        ("Hasselt H. Hartkerk", "Hasselt Heilig Hartkerk","01"),
        ("Heist Olvo", "Heist Olvo","14"),
        ("Herent De Becker Remystr.", "Herent De Becker Remystraat","01"),
        ("Herent Sergeystraat", "Herent Sergeystraat","40"),
        ("Herent Wijgmaalsestwg", "Herent Wijgmaalsesteenweg","01"),
        ("Herentals AZ Sint-Elisabeth", "Herentals AZ Sint-Elisabeth","01"),
        ("Herentals E. Claesstraat", "Herentals Ernest Claesstraat","01"),
        ("Herentals Lange Pad", "Herentals Langepad","01"),
        ("Herselt Blauberg kerk", "Herselt Blauberg Kerk","01"),
        ("Hever P. Benoitstraat", "Hever Peter Benoitstraat","01"),
        ("Hever P.Benoitstraat", "Hever Peter Benoitstraat","01"),
        ("Heverlee H.Hartinstituut", "Heverlee Heilig Hartinstituut","40"),
        ("Heverlee Jachtlaan", "Heverlee Jachtlaan","40"),
        ("Heverlee Kazerne (H. Hart)", "Heverlee Kazerne (Heilig Hart)","40"),
        ("Heverlee Leopold-III laan", "Heverlee Leopold III-laan", "40"), 
        ("Hingene P. Coomansstraat", "Hingene Pieter Coomansstraat", "44"), 
        ("Hoboken Dr. Coenstraat", "Dokter Coenstraat","01"),
        ("Hoboken P. H. Spaaklaan", "Paul Henri Spaaklaan","01"),
        ("Hoegaarden Brouw. Lorierstraat", "Hoegaarden Brouwerij Lorierstraat","01"),
        ("Hoeilaart D. Vander Vaerenstr.", "Hoeilaart Désiré Vandervaerenstraat", "42"),
        ("Hoeilaart E.Sohiestraat", "Hoeilaart Edgard Sohiestraat","42"),
        ("Hoeilaart G.De Kleermaekers", "Hoeilaart Guillaume De Kleermaekers","42"),
        ("Hoeilaart J.B.Delcortestraat", "Hoeilaart Jules Delcordestraat","42"),
        ("Hofstade t Steppeke", "Hofstade 't Steppeke","01"),
        ("Hoogstraten K. Boomstraat", "Hoogstraten Karel Boomstraat","01"),
        ("Houtain-St.-Siméon Route d' Heure", "Houtain-Saint-Siméon Route d'Heure","01"),
        ("Houtain-St.-Siméon Cite", "Houtain-Saint-Siméon Cité","01"),
        ("Hove R. Verbeecklaan", "Hove René Verbeecklaan","01"),
        ("Ieper Vti", "Ieper VTI","01"),
        ("Itegem Kerk (St-Guibertusplein)", "Itegem Kerk (Sint-Guibertusplein)","01"),
        ("Jette De Greef", "Guillaume De Greef","01"),
        ("Jeuk E. Beauduinstraat", "Jeuk Emile Beauduinstraat","01"),
        ("Jeuk H. Stassenstraat", "Jeuk Henri Stassenstraat","01"),
        ("Kalmthout R. Willemestraat", "Kalmthout René Willemestraat","01"),
        ("Kalmthout Kon. Elisabethstraat", "Kalmthout Koningin Elisabethstraat","01"),
        ("Kampenhout Huis nr. 34", "Kampenhout Huis nummer 34","01"),
        ("Kapellen Kon. Astridlaan", "Kapellen Koningin Astridlaan","01"),
        ("Keiheuvel Gt Kamping/Sporthal", "Keiheuvel Grote Camping/Sporthal","01"),
        ("Kessel-Lo De Becker Remypl.", "Kessel-Lo de Becker Remyplein","01"),
        ("Kessel-Lo H.Hartkerk", "Kessel-Lo Heilig Hartkerk","01"),
        ("Kessel-Lo Kerk H. Familie", "Kessel-Lo Kerk Heilige Familie","01"),
        ("Kessel-Lo L.Ruelensstraat", "Kessel-Lo Leopold Ruelensstraat","01"),
        ("Kessel-Lo P.Nollekensstraat", "Kessel-Lo Pieter Nollekensstraat","01"),
        ("Kessel-Lo Prov. Recreatiecentr.", "Kessel-Lo Provinciaal Recreatiecentrum","01"),
        ("Kester C. Verhavert", "Kester Cypriaan Verhavert","01"),
        ("Koksijde A.Bliecklaan", "Koksijde Albert Bliecklaan","01"),
        ("Koolkerke Fort Van Beieren", "Koolkerke Fort van Beieren","01"),
        ("Kortrijk L. Robbeplein", "Kortrijk Louis Robbeplein","01"),
        ("Kraainem Kon.Astridlaan", "Kraainem Koningin Astridlaan","01"),
        ("Kruiskerke  De Wante", "Kruiskerke De Wante","01"),
        ("Landen E. Moyaertslaan", "Landen Emile Moyaertslaan","01"),
        ("Ledegem In 'T Paard", "Ledegem In 't Paard","01"),
        ("Leest  Dorp", "Leest Dorp","01"),
        ("Lembeke D'Alcantaralaan", "Lembeke d'Alcantaralaan","01"),
        ("Leopoldsburg Hoek Ijzerlei", "Leopoldsburg Hoek IJzerlei","01"),
        ("Leopoldsburg Kon. Astridplein", "Leopoldsburg Koningin Astridplein","01"),
        ("Leuven H.Hartkliniek", "Leuven Heilig Hartkliniek","01"),
        ("Leuven Ijzerenmolenstraat", "Leuven IJzerenmolenstraat","01"),
        ("Leuven J.Stasstraat", "Leuven Jan Stasstraat","01"),
        ("Leuven Naamse Poort", "Leuven Naamsepoort","01"),
        ("Leuven O.L.V.Middelareskerk", "Leuven Onze-Lieve-Vrouw-Middelareskerk","01"),
        ("Leuven Tervuurse Poort", "Leuven Tervuursepoort","01"),
        ("Leuven Tiense Poort", "Leuven Tiensepoort","01"),
        ("L'Ecluse Chapelle", "L'Écluse Chapelle","01"),
        ("Lier Lisp kerk", "Lier Lisp Kerk","01"),
        ("Linden J.Davidtsstraat", "Linden Jan Davidtsstraat","01"),
        ("Liège Eglise Saint-Walburge", "Église Sainte-Walburge","01"),
        ("Liège Place J. De Wilde", "Place Jean De Wilde","01"),
        ("Liège Rue Jambede Bois", "Rue Jambe de Bois","01"),
        ("Liezele A. Piessensstraat", "Liezele Alfons Piessensstraat", "47"),
        ("Loenhout Stwg. Neerven", "Loenhout Steenweg Neerven","01"),
        ("Lokeren T Lavertje", "Lokeren 't Lavertje","01"),
        ("Marke Ijzeren Poort", "Marke IJzeren Poort","01"),
        ("Mechelen M. Gandhistraat", "Mechelen Mahatma Gandhistraat","01"),
        ("Mechelen M. Sabbestraat", "Mechelen Maurits Sabbestraat","01"),
        ("Mechelen O. Van Kesbeeckstraat", "Mechelen Oscar Van Kesbeeckstraat","01"),
        ("Mechelen W. Geetsstraat", "Mechelen Willem Geetsstraat","01"),
        ("Meerdonk St-Kornelisstraat", "Meerdonk Sint-Kornelisstraat","01"),
        ("Meerhout Gestel kerk", "Meerhout Gestel Kerk","01"),
        ("Meerle Burg. Van Nuetenstraat", "Meerle Burgemeester Van Nuetenstraat","01"),
        ("Meerle Dorp", "Meerledorp","01"),
        ("Meerle Groot Eysel Kabien", "Meerle Groot Eyssel Kabien","01"),
        ("Melsbroek Lt. Philippartstraat", "Melsbroek Luitenant Philippartstraat","01"),
        ("Menen 'T Veer 3", "Menen 't Veer 3","23"),
        ("Menen Barriere", "Menen Barrière","23"),
        ("Menen Station perron 2 afstaphalte", "Menen Station Perron 2 afstaphalte", "23"), 
        ("Merelbeke Kon. Elisabethlaan", "Merelbeke Koningin Elisabethlaan","01"),
        ("Merksem F. Adriaenssensstraat", "Frans Adriaenssensstraat","01"),
        ("Merksem J. Palfijnziekenhuis", "Jan Palfijnziekenhuis","01"),
        ("Merksplas Stwg. op Wortel", "Merksplas Steenweg op Wortel","01"),
        ("Mesen Au Pelerin", "Mesen Au Pèlerin","01"),
        ("Minderhout Bredaseweg (piloot bediening MSD)", "Minderhout Bredaseweg","01"),
        ("Mo Spoorwegbrug", "Moelingen Spoorwegbrug","01"),
        ("Moerzeke D'Hebbe", "Moerzeke d'Hebbe","01"),
        ("Moeskroen Boomkwekerijstraat", "Rue de la Pépinière","01"),
        ("Moeskroen Busstation", "Gare routière","01"),
        ("Moeskroen Coq Anglais", "Coq anglais","01"),
        ("Moeskroen Gerechtsplein", "Place de la Justice","01"),
        ("Moeskroen Hospitaal", "Hôpital","01"),
        ("Moeskroen Koninklijke Laan", "Avenue Royale","01"),
        ("Moeskroen Leopoldstraat", "Rue Léopold","01"),
        ("Moeskroen Luxemburgstraat", "Rue du Luxembourg","01"),
        ("Moeskroen Marktplein", "Place du Marché","01"),
        ("Moeskroen Metropole", "Métropole","01"),
        ("Moeskroen Nmbs-Station", "Gare SNCB","01"),
        ("Moeskroen Petit Cornil", "Petit-Cornil","01"),
        ("Moeskroen Petit Pont", "Petit-Pont","01"),
        ("Moeskroen Phenix", "Phoenix","01"),
        ("Moeskroen Picardieplaats", "Place Picardie","01"),
        ("Mol Gompel Kerkhof", "Gompel Kerkhof","01"),
        ("Mol Krpt. Achterbos", "Mol Kruispunt Achterbos","01"),
        ("Moorsel O.L.V. Kapel", "Moorsel Onze-Lieve-Vrouwkapel","01"),
        ("Mortsel T. Reynlaan", "Theofiel Reynlaan","01"),
        ("Muizen J. Van Geelstraat", "Muizen Jan Frans van Geelstraat","01"),
        ("Neerijse Stwg. nr.Leefdaal", "Neerijse Steenweg naar Leefdaal","01"),
        ("Niel E. Vanderveldelaan", "Niel Emile Vanderveldelaan","01"),
        ("Oevel E. Lauder", "Oevel Estée Lauder","01"),
        ("Olen P. Van Lommelstraat", "Olen P. van Lommelstraat","01"), # hard to find that first name
        ("Olen Sint-Jozef kerk", "Olen Sint-Jozef Kerk","01"),
        ("O.L.V.-Lombeek", "Onze-Lieve-Vrouw-Lombeek","01"),
        ("Onze-Lieve-Vrouw-Waver Uilelei", "Onze-Lieve-Vrouw-Waver Uilelei","01"),
        ("Oostende Dr.Verhaeghestraat", "Oostende Dokter Verhaeghestraat","01"),
        ("Oostende Th.Van Loostraat", "Oostende Thomas Van Loostraat","01"),
        ("Oostkamp A. Rodenbachstraat", "Oostkamp Albrecht Rodenbachstraat","01"),
        ("Oostmalle G. Gezellelaan", "Oostmalle Guido Gezellelaan","01"),
        ("Oostmalle P. Hensstraat", "Oostmalle Pater Hensstraat","01"),
        ("Opwijk Schoolcampus Vko", "Opwijk Schoolcampus VKO","01"),
        ("Oud-Heverlee Dr. Vandenborght", "Oud-Heverlee Dokter Vandenborght","01"),
        ("Oud-Turnhout Burg. Luytenstraat", "Oud-Turnhout Burgemeester Luytenstraat","01"),
        ("Oud-Turnhout Oosthoven kerk", "Oud-Turnhout Oosthoven Kerk","01"),
        ("Overboelare K. De Lensstraat", "Overboelare Karel Lodewijk de Lensstraat","01"),
        ("Overijse Cl. Vanophemstraat", "Overijse Clement Vanophemstraat","01"),
        ("Overijse E.Carelsstraat", "Overijse Emile Carelsstraat","01"),
        ("Overijse J.de Meeusstraat", "Overijse Graaf Joseph De Meeusstraat","01"),
        ("Overijse Lod. Gunslaan", "Overijse Louis Gunslaan","01"),
        ("Overijse Terhulpsestwg/Smetslaan", "Overijse Terhulpsesteenweg/Smetslaan","01"),
        ("Paal Azaleastraat", "Paal Azaleastraat","01"),
        ("Perk Stwg.Tervuren /Stwg.Vilvoorde", "Perk Steenweg Tervuren/Steenweg Vilvoorde","01"),
        ("Putte E. Claeslaan", "Putte Ernest Claeslaan","01"),
        ("Puurs Hof Ten Berg", "Puurs Hof-ten-Berg","01"),
        ("Puurs d' Hand", "Puurs d'Hand","01"),
        ("Ramsel Kerk Westmeerbeeksestwg.", "Ramsel Kerk Westmeerbeeksesteenweg","01"),
        ("Ramsel Truitseinde Aarschotsestwg.", "Ramsel Truitseinde Aarschotsesteenweg","01"),
        ("Ramsel Truitseinde Vandenheuvelstr.", "Ramsel Truitseinde Vandenheuvelstraat","01"),
        ("Ransberg Stg. naar Budingen", "Ransberg Steenweg naar Budingen","01"),
        ("Reet 's-Herenbaan", "Reet 's Herenbaan","01"),
        ("Reet P. Benoitlaan", "Reet Peter Benoitlaan","01"),
        ("Reusel Ned. Grens Reusel", "Reusel Nederlandse Grens","01"),
        ("Roesbrugge Dr. Gheysenstraat", "Roesbrugge Dokter Joseph Gheysenstraat","01"),
        ("Roeselare A.Rodenbachstraat", "Roeselare Albrecht Rodenbachstraat","01"),
        ("Roeselare K. Roelandstraat", "Roeselare Klokke Roelandstraat","01"),
        ("Roeselare Kliniek H.Hart", "Roeselare Kliniek Heilig Hart","01"),
        ("Roeselare Kta", "Roeselare KTA","01"),
        ("Roeselare Maria'S Rustoord", "Roeselare Maria's Rustoord","01"),
        ("Ronse/Renaix  H.Consciencestraat", "Hendrik Consciencestraat","01"),
        ("Ronse/Renaix A.Demanezstraat", "Albert Demanezstraat","01"),
        ("Ronse/Renaix C.Meunierstraat", "Constantin Meunierstraat","01"),
        ("Ronse/Renaix E.Soudansquare", "Eugène Soudansquare","01"),
        ("Ronse/Renaix R.Schumanstraat", "Robert Schumanstraat","01"),
        ("Ronse/Renaix Stijn Streuvelstraat", "Stijn Streuvelsstraat","01"),
        ("Ronse/Renaix Vandewielelaan", "Gomar Vandewielelaan","01"),
        ("Roosbeek Statiestr. Roosbeek", "Roosbeek Statiestraat Roosbeek","01"),
        ("Rotselaar Stwg op Wezemaal", "Rotselaar Steenweg op Wezemaal","01"),
        ("Ruisbroek J. De Donckerlaan", "Ruisbroek Jan De Donckerlaan","01"),
        ("Ruiselede 'T Zwijntje", "Ruiselede 't Zwijntje","01"),
        ("Rumbeke 'T Vosken", "Rumbeke 't Vosken","01"),
        ("Sas Van Gent (Nl) Suikerplein", "Sas van Gent Suikerplein","01"),
        ("Schoten E. Steursstraat", "Schoten Eduard Steursstraat","01"),
        ("Schoten J. Jennesstraat", "Schoten Jozef Jennesstraat","01"),
        ("Schoten Th. V. Cauwenberghslei", "Schoten Theofiel Van Cauwenberghslei","01"),
        ("Sint-Agatha-Berchem Marg.v.Oostenrijk", "Margaretha van Oostenrijk - Marguerite d'Autriche","01"),
        ("Sint-Antonius A. Vesaliuslaan", "Sint-Antonius Andreas Vesaliuslaan","01"),
        ("Sint-Baafs-Vijve Electr. Kabien", "Sint-Baafs-Vijve Electrische Kabien","01"),
        ("Sint-Job-in-'t Goor  Zandgroefweg", "Sint-Job-in-'t-Goor Zandgroefweg","01"),
        ("Sint-Job-in-'t Goor Inst. Kristus Koning", "Sint-Job-in-'t-Goor Instituut Kristus Koning","01"),
        ("Sint-Joris-Winge Glabbeeksestwg", "Sint-Joris-Winge Glabbeeksesteenweg","01"),
        ("Sint-Katelijne-Waver  Kouterdreef", "Sint-Katelijne-Waver Kouterdreef","01"),
        ("Sint-Kruis 'T Apertje", "Sint-Kruis 't Apertje","01"),
        ("Sint-Kruis Bos En Lommer", "Sint-Kruis Bos en Lommer","01"),
        ("Sint-Kruis J.Dooghelaan", "Sint-Kruis Julius Dooghelaan","01"),
        ("Sint-Kruis K. V. Manderstraat", "Sint-Kruis Karel Van Manderstraat","01"),
        ("Sint-Michiels 'T Speelhof", "Sint-Michiels 't Speelhof","01"),
        ("Sint-Michiels Baron De Serret", "Sint-Michiels Baron de Serret","01"),
        ("Sint-Michiels PZ Onze Lieve Vrouw", "Sint-Michiels Psychiatrisch Ziekenhuis Onze-Lieve-Vrouw","01"),
        ("Sint-Michiels Park De Rode Poort", "Sint-Michiels Park de Rode Poort","01"),
        ("Sint-Niklaas H. Familie", "Sint-Niklaas Heilige Familie","01"),
        ("Sint-Niklaas O.L.V. Plein", "Sint-Niklaas Onze-Lieve-Vrouwplein","01"),
        ("Sint-Niklaas P. Copstraat", "Sint-Niklaas Pastoor Copstraat","01"),
        ("Sint-Niklaas Prinses J. Charlottelaan", "Sint-Niklaas Prinses Josephine Charlottelaan","01"),
        ("Sint-Pieters-Kapelle Diksmuidestr. 112", "Sint-Pieters-Kapelle Diksmuidestraat 112","01"),
        ("SMV Rijkswacht", "Sint-Martens-Voeren Rijkswacht","01"),
        ("Stekene Ijzerhandstraat", "Stekene IJzerhandstraat","01"),
        ("Sterrebeek L.Nantierlaan", "Sterrebeek Leopold Nantierlaan","01"),
        ("Tessenderlo Tessenderlo Chemie", "Tessenderlo Chemie","01"),
        ("TIELT A. VAN ZANDVOORDESTRAAT", "Tielt Van Zandvoordestraat","01"),
        ("TIELT TRAMSTRAAT", "Tielt Tramstraat","01"),
        ("Tervuren O.Leuvense Baan", "Tervuren Oude Leuvense Baan","01"),
        ("Tervuren Ringl./Jachtl.", "Tervuren Ringlaan/Jachtlaan","01"),
        ("Tervuren Stg.op Brussel/Albert", "Tervuren Steenweg op Brussel/Albert","01"),
        ("Testelt Pl. Vondel", "Testelt Plaats Vondel","01"),
        ("Tienen O.L.V.-ten-Steen", "Tienen Onze-Lieve-Vrouw-ten-Steen","01"),
        ("Tienen Station Perron 1", "Tienen Station Perron 1","01"),
        ("Tisselt J. De Blockstraat", "Tisselt Jozef De Blockstraat","01"),
        ("Wemmel Cdt. J. De Blockplein", "Wemmel Commandant J. de Blockplein","01"),
        ("Torhout 'T Ruytershof", "Torhout 't Ruytershof","01"),
        ("Torhout Torhoutsesteenweg Huis Nr.21", "Torhout Torhoutsesteenweg Huis nummer 21","01"),
        ("Tremelo E. Van Der Veldestraat", "Tremelo Emiel Van Der Veldestraat","01"),
        ("Tremelo Ger. Centrum P. Damiaan", "Tremelo Geriatrisch Centrum Pater Damiaan","01"),
        ("Tremelo Vondelpark nr 2A", "Tremelo Vondelpark nummer 2A","99"),
        ("Turnhout A. Rodenbachplantsoen", "Turnhout Albrecht Rodenbachplantsoen","01"),
        ("Turnhout G. Gezellestraat", "Turnhout Guido Gezellestraat","01"),
        ("Turnhout Sint-Pieterinstituut", "Turnhout Sint-Pietersinstituut","01"),
        ("Turnhout Stwg. op Zondereigen", "Turnhout Steenweg op Zondereigen","01"),
        ("Ukkel Pijnbomenstraat", "Pijnbomenweg","01"),
        ("Veurne J.P. Davidlaan", "Veurne Jan Baptist Davidlaan","01"),
        ("Vilvoorde Houtemsestwg 191", "Vilvoorde Houtemsesteenweg 191","01"),
        ("Vilvoorde Houtemsestwg 266", "Vilvoorde Houtemsesteenweg 266","01"),
        ("Visé Place des Déportes", "Visé Place des Déportés","01"),
        ("Visé Gare Ir", "Visé Gare IR","01"),
        ("Visé Allee des Acacias", "Visé Allee des Acacias", "42"),
        ("Vissenaken Waterstr", "Vissenaken Waterstraat","01"),
        ("Vollezele Stwg naar Galmaarden", "Vollezele Steenweg naar Galmaarden","01"),
        ("Voormezele O. Mesenstwg.", "Voormezele Oude Mesensesteenweg","01"),
        ("Voortkapel Stwg. Voortkapel", "Voortkapel Steenweg Voortkapel","01"),
        ("Vorst Kleinstraat", "Vorst Kleinstraat","79"),
        ("Vorst Borgtstraat", "Vorst Borgtstraat","80"),
        ("Vorst Monaco", "Monaco","20"),
        ("Waardamme  Veldhoekstraat nr 108", "Waardamme Veldhoekstraat nummer 108","01"),
        ("Waarloos J. B. Francisstraat", "Waarloos Jan Baptist Francisstraat","01"),
        ("Waasmunster K. Astridstraat", "Waasmunster Koningin Astridstraat","01"),
        ("Waasmunster Ocmw", "Waasmunster OCMW","01"),
        ("Wachtebeke Dom. Puyenbroek P1", "Wachtebeke Domein Puyenbroek P1","01"),
        ("Wachtebeke Gebr. Naudtslaan", "Wachtebeke Gebroeders Naudtslaan","01"),
        ("Waver Av. des Mesanges", "Waver Avenue des Mésanges","01"),
        ("Weelde Stwg. op Zondereigen", "Weelde Steenweg op Zondereigen","01"),
        ("Welle Pr. Daenslaan", "Welle Priester Daenslaan","01"),
        ("Wemmel H. de Keersmaekerlaan", "Wemmel H. De Keersmaekerlaan","20"),
        ("Wemmel I.Meyskens", "Wemmel Isidoor Meyskens","01"),
        ("Wemmel Kon. Astridlaan", "Wemmel Koningin Astridlaan","01"),
        ("Wervik Cafe 'T Voske", "Wervik Cafe 't Voske","01"),
        ("Wespelaar Weg nr. Wakkerzeel", "Wespelaar Weg naar Wakkerzeel","01"),
        ("Wetteren Kon. Astridlaan", "Wetteren Koningin Astridlaan","01"),
        ("Wijgmaal Rotselaarsestwg 84", "Wijgmaal Rotselaarsesteenweg 84","01"),
        ("Willebroek H. Vosstraat", "Willebroek Herman Vosstraat","01"),
        ("Wilrijk Dr. Donnyplein", "Dokter Donnyplein","01"),
        ("Wilrijk Dr. Veeckmanslaan", "Dokter Veeckmanslaan","01"),
        ("Wilrijk F. Van Dunlaan", "Frans van Dunlaan","01"),
        ("Wilrijk J. Moretuslei", "Jules Moretuslei","01"),
        ("Wilsele L.Woutersstraat", "Wilsele Louis Woutersstraat","01"),
        ("Wilsele Weggevoerdenstr.", "Wilsele Weggevoerdenstraat","01"),
        ("Wilsele Wijgm.stwg./Transf.", "Wilsele Wijgmaalsesteenweg/Transformatorstation","01"),
        ("Wingene 'T Leestje", "Wingene 't Leestje","01"),
        ("Wintam F. De Laetstraat", "Wintam Frans De Laetstraat","01"),
        ("Wintam V. Kegelsstraat", "Wintam Victor Kegelsstraat","01"),
        ("Wolvertem Besch.Werkplaats", "Wolvertem Beschermde Werkplaats","01"),
        ("Wolvertem Brussegemse Stwg.", "Wolvertem Brussegemse Steenweg","01"),
        ("Wolvertem Rossem,Dorp", "Wolvertem Rossem, Dorp","01"),
        ("Wuustwezel G. Gezellelaan", "Wuustwezel Guido Gezellelaan","01"),
        ("Zaffelare T'Jongestraat", "Zaffelare 't Jongestraat","01"),
        ("Zeebrugge Weg Op Zwankendamme", "Zeebrugge Weg op Zwankendamme","01"),
        ("Zoersel G. Gezellelaan", "Zoersel Guido Gezellelaan","01"),
        ("Zwartberg G. Lambertlaan", "Zwartberg Guillaume Lambertlaan","01"),
          )

    def testNameConversionKnownValues(self):                          
        """NameConversion should give known result with known input"""
        for orig, expanded, zone in self.knownValues:
            result = delijnosmlib.nameconversion(orig,zone)
            if result != expanded:
                print(orig + ' -> ' + result + ' -> ' + repr(expanded))
                print('''    (500,0,r"''' + orig + '","' + expanded + '","01"),')
                r = Tk()
                # r.withdraw()
                # r.clipboard_clear()
                r.clipboard_append(result.split(' ')[-1].replace('straat','').replace('laan','').replace('plein','').replace('lei','').replace('steenweg','').replace('weg',''))
                # r.destroy()

            self.assertEqual(result, expanded)                  

if __name__ == "__main__":
    unittest.main()            